[package]
name = "encrypted_channels_integrity"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "encrypted_channels_integrity"

[dependencies]
hdi = { workspace = true }
serde = { workspace = true }

locker_types = { path = "../../../../../crates/locker_types" }
